---
title: "rachaelku_A4"
author: "Rachael Ku"
date: "10/18/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning = F, message = F)
```

```{r}
library(tidyverse)
library(censusapi)
Sys.setenv(CENSUS_KEY="4e13a5273cf526d80ab8ce9b078d92794e60da99")

acs_vars_2019_5yr <-
  listCensusMetadata(
    name = "2019/acs/acs5",
    type = "variables"
  )
```


```{r}
race_categories <- c(
  "White alone",
  "Black or African American alone",
  "American Indian and Alaska Native alone",
  "Asian alone",
  "Native Hawaiian and Other Pacific Islander alone",
  "Some Other Race alone",
  "Two or more Races"
)
```

```{r}
bay_educ_race_2019 <-
  1:7 %>% 
  map_dfr(function(x){
    getCensus(
      name = "acs/acs5",
      vintage = 2019,
      region = "county:001,013,041,055,075,081,085,095,097",
      regionin = "state:06",
      vars = paste0("group(C15002",LETTERS[x],")")
    ) %>%
      select(!c(GEO_ID,state,NAME) & !ends_with(c("EA","MA","M"))) %>%
      pivot_longer(
        ends_with("E"),
        names_to = "name",
        values_to = "estimate"
      ) %>%
      left_join(
        acs_vars_2019_5yr %>% 
          select(name, label)
      ) %>% 
      select(-name) %>% 
      separate(
        label,
        into = c(NA,NA,NA,"education"),
        sep = "!!"
      ) %>% 
      filter(!is.na(education)) %>% 
      mutate(race = race_categories[x])
  })
```


```{r}
bay_race_total <-
  bay_educ_race_2019 %>% 
  group_by(race) %>% 
  summarize(estimate = sum(estimate)) %>% 
  mutate(income = "Total")

bay_educ_race_2019 %>% 
  group_by(education, race) %>% 
  summarize(estimate = sum(estimate)) %>% 
  rbind(bay_race_total) %>% 
  ggplot() +
  geom_bar(
    aes(
      x = education %>% factor(levels = rev(c("Total",unique(bay_educ_race_2019$education)))),
      y = estimate,
      fill = race %>% factor(levels = rev(unique(bay_educ_race_2019$race)))
    ),
    stat = "identity",
    position = "fill"
  ) +
  labs(
    x = "Educational Attainment",
    y = "Proportion of households",
    title = "Bay Area household income by race",
    fill = "Race of householder"
  ) +
  coord_flip() +
  theme(
    legend.position = "bottom",
    legend.direction = "vertical"
  )  +
  guides(
    fill = guide_legend(
      reverse = T
    )
  )
```


```{r}
# part 2

bay_educ_2019 <- getCensus(
  name = "acs/acs5",
  vintage = "2019",
  region = "county:001,013,041,055,075,081,085,095,097",
  regionin = "state:06",
  vars = "group(C15002A)"
  ) %>%
  select(ends_with("E") & -c(state, NAME)) %>%
  summarize_all(sum) %>%
  pivot_longer(
    everything(),
    names_to = "name",
    values_to = "estimate"
  ) %>%
  left_join(
    acs_vars_2019_5yr %>% select(name, label),
    ) %>%
  separate(
    label, 
    into = c(NA, NA, NA, "yrsed"),
    sep = "!!"
  ) %>%
  select(-name) %>%
  filter(!is.na(yrsed)) %>%
  mutate(
    race = "white alone"
  )



```






