---
title: "rachaelku_A2"
author: "Rachael Ku"
date: "10/5/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning = F, message = F)
```

```{r}
library(tidyverse)
library(sf)
library(tigris)
library(mapview)
library(censusapi)
library(leaflet)
```

```{r}
ca_counties <- counties("CA", cb = T, progress_bar = F)
st_crs(ca_counties)
```

```{r}
Sys.setenv(CENSUS_KEY="4e13a5273cf526d80ab8ce9b078d92794e60da99")

smc_pop_2020 <-
  getCensus(
    name = "dec/pl",
    vintage = 2020,
    region = "block:*", 
    regionin = "state:06+county:081",
    vars = "P1_001N"
  ) %>% 
  transmute(
    block =
      paste0(state,county,tract,block),
    pop = P1_001N
  )

```


```{r}

ca_cities <- places("CA", cb = T, progress_bar = FALSE)

library(devtools)
install_github('walkerke/tigris')
library(tigris)

smc_blocks_2020 <- blocks("CA", "San Mateo", year = 2020, progress_bar = F)

epa_boundary <- places("CA", progress_bar = F) %>% 
  filter(NAME == "East Palo Alto")

epa_pop_2020 <- smc_pop_2020 %>% 
  left_join(smc_blocks_2020 %>% select(block = GEOID20)) %>% 
  st_as_sf() %>% 
  st_centroid() %>% 
  .[epa_boundary, ] %>% 
  st_set_geometry(NULL) %>% 
  left_join(smc_blocks_2020 %>% select(block = GEOID20)) %>% 
  st_as_sf()

mapview(epa_pop_2020, zcol = "pop")
```

```{r}
smc_blocks_2010 <- blocks("CA", "San Mateo", year = 2010, progress_bar = F)

smc_pop_2010 <-
  getCensus(
    name = "dec/pl",
    vintage = 2010,
    region = "block:*", 
    regionin = "state:06+county:081",
    vars = "P003001"
  ) %>% 
  transmute(
    block =
      paste0(state,county,tract,block),
    pop = P003001
  )

epa_pop_2010 <- smc_pop_2010 %>% 
  left_join(smc_blocks_2010 %>% select(block = GEOID10)) %>% 
  st_as_sf() %>% 
  st_centroid() %>% 
  .[epa_boundary, ] %>% 
  st_set_geometry(NULL) %>% 
  left_join(smc_blocks_2010 %>% select(block = GEOID10)) %>% 
  st_as_sf()
```

```{r}
epa_pop_2010_2020 <- st_join(
  epa_pop_2020, 
  epa_pop_2010, 
  join = st_intersects,
  suffix = c("2020", "2010"),
  left = TRUE,
  largest = FALSE
)

epa_pop_2010_2020 <- 
  mutate(epa_pop_2010_2020,
    pop_change = (epa_pop_2010_2020$pop2020 - epa_pop_2010_2020$pop2010)/ epa_pop_2010_2020$pop2010 * 43560
  )
```

```{r}
palette <- colorNumeric(palette = rev("RdPu"), domain = NULL, na.color = NA)
leaflet() %>% 
  addPolygons(
    data = epa_boundary,
    stroke = F
  ) %>%
  addPolygons(
    data = epa_pop_2010_2020,
    weight = 0.75,
    fillColor = ~palette(pop_change)
  ) 
```








